version: '3.4'

services:
  ocelotapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  morvie-review.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

